const express = require('express');
const router = express.Router();
const { askGemini } = require('../services/aiService');

// ✅ FIXED IMPORT: Destructure the named export
const { sqlcmdQuery } = require('../db/sqlcmdQuery');

router.post('/ask', async (req, res) => {
    try {
        const { question } = req.body;
        console.log(`🤖 AI Request: "${question}"`);

        // Step 1: Get AI response
        const aiResponse = await askGemini(question);
        console.log('📋 AI Response:', JSON.stringify(aiResponse, null, 2));

        if (aiResponse.error) {
            console.error('❌ AI Error:', aiResponse.error);
            return res.json({ error: aiResponse.error });
        }

        if (aiResponse.sql) {
            console.log(`⚡ Executing SQL: ${aiResponse.sql}`);

            // Step 2: Execute SQL query
            const data = await sqlcmdQuery(aiResponse.sql);
            console.log(`✅ Query returned ${data.length} rows`);

            // Step 3: Validate data
            if (!data || data.length === 0) {
                console.warn('⚠️ No data returned from query');
                return res.json({
                    answer: "Query executed successfully, but no data was found for the requested time period.",
                    chartConfig: aiResponse.chartConfig,
                    data: []
                });
            }

            // Step 4: Return successful response
            return res.json({
                answer: `Found ${data.length} data points`,
                chartConfig: aiResponse.chartConfig,
                data: data
            });
        }

        console.error('❌ No SQL generated by AI');
        return res.status(500).json({ error: "AI did not generate a valid SQL query" });

    } catch (error) {
        console.error("❌ Route Error:", error);
        res.status(500).json({ error: error.message || "Internal server error" });
    }
});

module.exports = router;